name: CI

on:
  push:
    branches:
    - master
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
    - run: npm install
    - name: Publish
      if: success()
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}